config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'
  get 'about' => 'about#index'
  get 'service' => 'service#index'
  get 'portfolio' => 'portfolio#index'
  get 'portfolio/:id' => 'portfolio#show', :as => :show_portfolio
  get 'links' => 'links#index'
  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'

  resources :posts, :only => [:show]

  root :to => 'home#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title S & S Homes, Inc.
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-9687987-21']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  %body{:'data-controller' => params[:controller]}
    .container
      %header
        .logo
          %h1
            %a{:href => '/'} S&S Homes, Inc.
        .nav
          %nav
            = link_to 'Home', home_path, :class => "#{'selected' if params[:controller] == 'home'}"
            = link_to 'About Us', about_path, :class => "#{'selected' if params[:controller] == 'about'}"
            = link_to 'Services', service_path, :class => "#{'selected' if params[:controller] == 'service'}"
            = link_to 'Portfolio', portfolio_path, :class => "#{'selected' if params[:controller] == 'portfolio'}"
            = link_to 'Blog', 'http://blog.sshomesincorporated.com'
            = link_to 'Links', links_path, :class => "#{'selected' if params[:controller] == 'links'}"
            = link_to 'Contact', contact_path, :class => "#{'selected' if params[:controller] == 'contact'}"
        .social
          - unless social_nav.nil?
            %nav
              - social_nav.links.asc(:index).each do |link|
                = link_to image_tag(link.image.url, :size => '28x28'), link.url
      - unless flash.empty?
        .flash
          - if flash[:notice]
            %p.notice= flash[:notice]
          - if flash[:alert]
            %p.alert= flash[:alert]
      = yield
    %footer
      .container
        .left
          %span &copy; 2013 S & S Homes, Inc.
        .right
          %span
            = mail_to 'scott@sshomesincorporated.com'
          %span (402) 202-6527